---

- name: install dependencies
  yum: name=docker-python state=present


- name: download ose container images
  docker_image:
    name: "{{ src_registry }}/{{ item }}"
  with_items:
    - "{{ ose_core_images }}"
    - "{{ ose_infra_images }}"
    - "{{ cns_core_images }}"

...
