---

# vim: set ft=ansible:

  - name: Pulling the workshopper docker image
    docker_image:
      name: osevg/workshopper:0.2

  - name: put the systemd-docker binary file at /usr/bin
    copy:
      src: systemd-docker
      dest: /usr/local/sbin/
      mode: u+x,g=r,o=r
      owner: root
      group: root

  - name: create workshopper systemd service
    copy:
      src: workshopper.service
      dest: /etc/systemd/system/

  - name: copy the config file containing environment variables and URLs
    copy:
      src: workshopper
      dest: /etc/sysconfig/

...
