---
- name: persist iptables rules required for GlusterFS
  lineinfile:
    dest: /etc/sysconfig/iptables
    line: "{{ item }}"
    insertbefore: "^COMMIT"
  with_items:
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24010 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 3260 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24007 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24008 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2222 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m multiport --dports 49152:49664 -j ACCEPT"

- name: configure firewall at runtime
  shell: "iptables {{ item }}"
  with_items:
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24010 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 3260 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24007 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24008 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2222 -j ACCEPT"
    - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m multiport --dports 49152:49664 -j ACCEPT"

- name: install dependencies
  yum: name={{ item }} state=present
  with_items:
    - iscsi-initiator-utils
    - device-mapper-multipath

- name: enable multipathing
  shell: mpathconf --enable
  args:
    creates: /etc/multipath.conf

- name: configure iscsi multipathing
  blockinfile:
    path: /etc/multipath.conf
    block: |
     devices {
              device {
                      vendor "LIO-ORG"
                      user_friendly_names "yes"
                      path_grouping_policy "failover"
                      path_selector "round-robin 0"
                      failback immediate
                      path_checker "tur"
                      prio "const"
                      no_path_retry 120
                      rr_weight "uniform"
              }
      }

- name: load required kernel modules
  modprobe: name={{ item }} state=present
  with_items:
    - dm_thin_pool
    - dm_multipath
    - target_core_user

- name: ensure kernel modules load a boot
  lineinfile:
    path: /etc/modules-load.d/{{ item }}.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - dm_thin_pool
    - dm_multipath
    - target_core_user

- name: add rpcbind to multi-user target
  shell: systemctl add-wants multi-user rpcbind.service
  args:
    creates: /etc/systemd/system/multi-user.target.wants/rpcbind.service

- name: start and enable rpcbind service
      service: name=rpcbind state=started enabled=yes

...
