env:
  global:
  - secure: "hCXKSfK0wYAToyAuNIXNgDgW7C49/MG17v6ZFpKLXakI/ZcMI/3eCqp2S3MsL94t627qxvwJF/0kXm9JE1b6VO83lmG0KmjyMi9uhOPxAfxoZIcT1h21qBGx12MuwHByCYkw9emoLK9slOU0SHaZmRfRJV6LnOMpClV4qLT/xoSWV2w6GkLepBIPxAaoXXqUtAyPkDHYOPWpY/dpZ56Zb9OOHxgA2qYnZsy0BG8g7dN6E7IdjNB1vh/+WdedhDGf2BBMjZGe/MqFdoCtMVhqgM3HR7VMFMopRJIqW1gRYB48p131MlG2pAmI0cVU1FgVRNN5ENc3vGEjgiVe2DtQmYLv0grIm/6B0BX49+CbzoN/EohzlIao8gUc2mQv1e7QeY4f114oo1q5qXECOEdaDQQbLBtBpyzGzuzDcUHgPvGjPZO9yGoHElLI3nsXf72ou0BHrs6A8fbpusNrZQZzeW0QoAiG6Yf4wBcxz9MjKDql41CdaRQYToQSt1rr/8pJfYWb9/DWEX2FjxywsbxlovZj/vt66uckHYfr0hSUfZjKN12HGeNC2v9LqPBpIroC0G6eV57HulyLhzyiZh9aRcLS7qKOp7tUnhJ5KC42UmEVR2DKBWBRJfDO1C6YkTjMXR3lhMUZR6H2PJQztYZnXR/4T9H5fZqN6QzlspsqfOE="
  - secure: "uoXHY5+smU0Whajy/to7qfDNzDpaIZyXhle2ggQqZipshTned7q6WnqDRiW6FM+HikW1TeLg/7rZ2R/3SA7Uwoll0QoQrFBrHwPnHEAvN3L4rdLoD1lMAmgWmV5IJ1kRqYAqG+MGq4y7l2Pf4SFBR930NWqCIdK18X4TlbklN1XVx0sG2O98KdIHLca5CX+SrwaKm4Nu0H/4sgbEtalSu/jLZMJ5E+zRUY+1Tvd2mv7ZxTZWK6LUNhKAGoV5hOgyz6aBjNSqKaWQ/OwgDpFHMCL6QJUnNrD4soj2QVGn87oqusXLjYXGK4u/m+qwwOiY8OAPv+1ndPAE0Msd98FmVDkVFUO2S8aA2MJetS0OvFa1eQ0/71amYSXMdWO1DoASwOJkVSKuaVpkOdf4zIpPS7t8pud2OYOZaOuLdhqxEuTcusrSDQKxklumMpzQhmHRZ/ElJ/KeqXxb9+5eackou62NOImIqqT/2cyzhb+WBS9z6LnyLL1ySqoFjxZb13z515apxdWejK7nUlhUmuvjToDX1Zft75JawNDbgrjzOhPIHKlUcegX3uw8gxZT/X6UQztMoS4+50066AQC97l4gjA5yELgAVvVsCBIHGQWhFpfhWNSQnk6KeHjgcWQwDAMUkRlSHvnJKakuZ5dIgZHFhzCrsZZhZPFc/KV+51SROc="
branches:
  except:
  - ci
language: ruby
before_install:
- sudo apt-get install -y jq
script:
- "./script.sh"
