---
osrelease: 3.11.98-1.git.0.0cbaff3
installer_release: 3.11.98-1.git.0.3cfa7c3 

ose_packages:
  - cockpit-docker
  - cockpit-ws
  - cockpit-system
  - cockpit-bridge
  - ansible
  - bash-completion
  - cifs-utils
  - dnsmasq
  - ntp
  - logrotate
  - httpd-tools
  - bind-utils
  - firewalld
  - libselinux-python
  - conntrack-tools
  - openssl
  - iproute
  - python-dbus
  - PyYAML
  - yum-utils
  - glusterfs-fuse
  - vim
  - wget
  - git
  - net-tools
  - iptables-services
  - bridge-utils
  - atomic
  - etcd
  - openshift-ansible-{{ installer_release }}.el7
  - openshift-ansible-playbooks-{{ installer_release }}.el7
  - openshift-ansible-roles-{{ installer_release }}.el7
  - openshift-ansible-docs-{{ installer_release }}.el7
  - atomic-openshift-{{ osrelease }}.el7.x86_64
  - atomic-openshift-node-{{ osrelease }}.el7.x86_64
  - atomic-openshift-excluder-{{ osrelease }}.el7.noarch
  - atomic-openshift-docker-excluder-{{ osrelease }}.el7.noarch
  - atomic-openshift-clients-{{ osrelease }}.el7.x86_64

storage_packages:
  - nfs-utils
  - glusterfs-fuse
  - ceph-common
  - iscsi-initiator-utils
  - device-mapper-multipath

...
