site_name: OpenShift Test Drive for Administrators
site_url: 'https://dmesser.github.io/openshift-cns-testdrive/'
site_favicon: 'img/favicon.ico'
copyright: 'Copyright Â©2017 Red Hat, Inc.'

theme: 'readthedocs'
extra:
  logo: 'img/shadowman_rgb.png'
  palette:
    primary: 'red'
    accent: 'light blue'

pages:
- Overview: index.md
