site_name: OpenShift for Ops Test Drive
site_url: 'https://dmesser.github.io/openshift-cns-testdrive/'
copyright: 'Copyright Â©2018 Red Hat, Inc.'

theme:
  name: 'readthedocs'
  custom_dir: 'custom_theme'
extra:
  logo: 'img/shadowman_rgb.png'
  palette:
    primary: 'red'
    accent: 'light blue'

pages:
- Overview: index.md
