---

- hosts: localhost

  tasks:

    - set_fact:
        idm_fqdn: "idm.internal.aws.testdrive.openshift.com"

    - name: wait for IDM server to be started
      wait_for:
        host: "{{ idm_fqdn }}"
        port: 22
        timeout: 600

    - name: wait for IDM LDAP service to be online
      wait_for:
        host: "{{ idm_fqdn }}"
        port: 389
        timeout: 600

    - name: ensure master configuration directory exists
      file:
        path: /etc/origin/master
        state: directory
        owner: root
        group: root
        mode: 0700


- hosts: idm

  tasks:

    - name: wait for IDM certificate to be generated
      wait_for:
        path: /etc/ipa/ca.crt
        timeout: 600

    - name: fetch IDM certificate
      fetch:
        src: /etc/ipa/ca.crt
        dest: /tmp/
        flat: yes

- hosts: localhost

  tasks:

    - name: copy IDM certificate to configuration directory
      copy:
        src: /tmp/ca.crt
        dest: /etc/origin/master/idm_ldap_ca.crt
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

...
