apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    ## Do last to overwrite default rather then other way arround
    argocd.argoproj.io/sync-wave: "99"
  name: config
spec:
  addon:
    params:
    - name: clusterTasks
      value: "true"
    - name: pipelineTemplates
      value: "true"
    - name: communityClusterTasks
      value: "true"
  chain:
    artifacts.taskrun.format: in-toto
    artifacts.taskrun.storage: tekton
    artifacts.taskrun.signer: x509
    artifacts.oci.storage: oci
    artifacts.oci.format: simplesigning
    artifacts.oci.signer: x509
    transparency.enabled: "true"
  dashboard:
    readonly: false
  params:
  - name: createRbacResource
    value: "true"
  pipeline:
    await-sidecar-readiness: true
    default-service-account: pipeline
    disable-affinity-assistant: true
    disable-creds-init: false
    enable-api-fields: beta
    enable-bundles-resolver: true
    enable-cluster-resolver: true
    enable-custom-tasks: true
    enable-git-resolver: true
    enable-hub-resolver: true
    enable-provenance-in-status: false
    enable-tekton-oci-bundles: false
    metrics.pipelinerun.duration-type: lastvalue
    metrics.pipelinerun.level: pipelinerun
    metrics.taskrun.duration-type: lastvalue
    metrics.taskrun.level: taskrun
    params:
    - name: enableMetrics
      value: "true"
    performance:
      disable-ha: false
    require-git-ssh-secret-known-hosts: false
    running-in-environment-with-injected-sidecars: true
    send-cloudevents-for-runs: false
    trusted-resources-verification-no-match-policy: ignore
    git-resolver-config:
      default-revision: main
      fetch-timeout: 1m
      default-url: https://github.com/gnunn-gitops/tekton-catalog
  platforms:
    openshift:
      pipelinesAsCode:
        enable: true
        settings:
          application-name: Pipelines as Code CI
          auto-configure-new-github-repo: "false"
          bitbucket-cloud-check-source-ip: "true"
          custom-console-name: ""
          custom-console-url: ""
          custom-console-url-pr-details: ""
          custom-console-url-pr-tasklog: ""
          error-detection-from-container-logs: "true"
          error-detection-max-number-of-lines: "50"
          error-detection-simple-regexp: ^(?P<filename>[^:]*):(?P<line>[0-9]+):(?P<column>[0-9]+):([
            ]*)?(?P<error>.*)
          error-log-snippet: "true"
          hub-catalog-name: tekton
          hub-url: https://api.hub.tekton.dev/v1
          remote-tasks: "true"
          secret-auto-create: "true"
          secret-github-app-token-scoped: "true"
  profile: all
  pruner:
    disabled: false
    keep: 100
    resources:
    - pipelinerun
    schedule: 0 8 * * *
  targetNamespace: openshift-pipelines
  trigger:
    default-service-account: pipeline
    enable-api-fields: stable
