---

- name: disable tty requirement for cloud-user
  lineinfile:
    line: Defaults:cloud-user !requiretty
    dest: /etc/sudoers
    state: present

- name: create ansible.cfg
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

...
