---
- name: create cloud-user account
  user:
    name: cloud-user

- name: create ssh directory
  file:
    path: /home/cloud-user/.ssh
    state: directory
    mode: 0700

- name: create ssh key pair for internal use
  shell:
    cmd: ssh-keygen -b 2048 -t rsa -f /home/cloud-user/.ssh/id_rsa -q -N ""
    creates: /home/cloud-user/.ssh/id_rsa

- name: change permissions on key pair
  file: path=/home/cloud-user/.ssh/{{ item }} owner=cloud-user group=cloud-user mode=0400
  with_items:
    - id_rsa
    - id_rsa.pub

- name: fetch ssh pub key
  fetch:
    src: /home/cloud-user/.ssh/id_rsa.pub
    dest: fetch/
    flat: yes

- name: fetch ssh private key
  fetch:
    src: /home/cloud-user/.ssh/id_rsa
    dest: fetch/
    flat: yes

- name: add ssh key pair to authorized_keys
  authorized_key:
    user: cloud-user
    key: "{{ lookup('file', 'fetch/id_rsa.pub') }}"
    state: present

...
