---

deploy_mirror: false
image_src: registry.redhat.io
ose_major_tag: v3.11.16
ose_release_tag: v3.11
cns_release_tag: v3.10
logging: v3.10.45-2
ose_deployer_tag: latest
image_source: registry.redhat.io

ose_core_images:
  - openshift3/csi-attacher:{{ ose_major_tag }}
  - openshift3/csi-driver-registrar:{{ ose_major_tag }}
  - openshift3/csi-livenessprobe:{{ ose_major_tag }}
  - openshift3/csi-provisioner:{{ ose_major_tag }}
#  - openshift3/efs-provisioner:{{ ose_major_tag }}
  - openshift3/image-inspector:{{ ose_major_tag }}
#  - openshift3/local-storage-provisioner:{{ ose_major_tag }}
#  - openshift3/manila-provisioner:{{ ose_major_tag }}
  - openshift3/ose-cli:{{ ose_major_tag }}
  - openshift3/ose-cluster-capacity:{{ ose_major_tag }}
  - openshift3/ose-deployer:{{ ose_major_tag }}
  - openshift3/ose-descheduler:{{ ose_major_tag }}
  - openshift3/ose-docker-builder:{{ ose_major_tag }}
  - openshift3/ose-docker-registry:{{ ose_major_tag }}
  - openshift3/ose-egress-dns-proxy:{{ ose_major_tag }}
  - openshift3/ose-egress-http-proxy:{{ ose_major_tag }}
  - openshift3/ose-egress-router:{{ ose_major_tag }}
#  - openshift3/ose-f5-router:{{ ose_major_tag }}
  - openshift3/ose-haproxy-router:{{ ose_major_tag }}
  - openshift3/ose-hyperkube:{{ ose_major_tag }}
  - openshift3/ose-hypershift:{{ ose_major_tag }}
  - openshift3/ose-keepalived-ipfailover:{{ ose_major_tag }}
  - openshift3/ose-pod:{{ ose_major_tag }}
  - openshift3/ose-docker-builder:{{ ose_major_tag }}
  - openshift3/ose-node-problem-detector:{{ ose_major_tag }}
  - openshift3/ose-recycler:{{ ose_major_tag }}
  - openshift3/ose-web-console:{{ ose_major_tag }}
  - openshift3/ose-node:{{ ose_major_tag }}
  - openshift3/ose-control-plane:{{ ose_major_tag }}
  - openshift3/registry-console:{{ ose_major_tag }}
  - openshift3/snapshot-controller:{{ ose_major_tag }}
  - openshift3/snapshot-provisioner:{{ ose_major_tag }}
  - rhel7/etcd
  - "openshift3/ose:latest"
  - "openshift3/ose:{{ ose_major_tag }}"
  - rhel7/etcd:latest

ose_infra_images:
  - "openshift3/logging-auth-proxy:{{ logging }}"
  - "openshift3/logging-auth-proxy:{{ logging }}"
  - "openshift3/logging-curator:{{ logging }}"
  - "openshift3/logging-elasticsearch:{{ logging }}"
  - "openshift3/logging-eventrouter:{{ logging }}"
  - "openshift3/logging-fluentd:{{ logging }}"
  - "openshift3/logging-kibana:{{ logging }}"
  - "openshift3/oauth-proxy:{{ ose_major_tag }}"
  - "openshift3/metrics-cassandra:{{ ose_major_tag }}"
  - "openshift3/metrics-hawkular-metrics:{{ ose_major_tag }}"
  - "openshift3/metrics-hawkular-openshift-agent:{{ ose_major_tag }}"
  - "openshift3/metrics-heapster:{{ ose_major_tag }}"
  - "openshift3/metrics-schema-installer:{{ ose_major_tag }}"
  - "openshift3/prometheus:{{ ose_major_tag }}"
  - "openshift3/prometheus:{{ ose_major_tag }}"
  - "openshift3/prometheus-alert-buffer:{{ ose_major_tag }}"
  - "openshift3/prometheus-alert-buffer:{{ ose_major_tag }}"
  - "openshift3/prometheus-node-exporter:{{ ose_major_tag }}"
  - "openshift3/prometheus-node-exporter:{{ ose_major_tag }}"
  - "openshift3/prometheus-alertmanager:{{ ose_major_tag }}"
  - "openshift3/ose-deployer:{{ ose_major_tag }}"
  - "openshift3/ose-deployer:{{ ose_major_tag }}"
  - "openshift3/logging-deployer:{{ ose_deployer_tag }}"
  - "openshift3/metrics-deployer:{{ ose_deployer_tag }}"

cns_core_images:
  - "rhgs3/rhgs-volmanager-rhel7:{{ cns_release_tag }}"
  - "rhgs3/rhgs-server-rhel7:{{ cns_release_tag }}"
  - "rhgs3/rhgs-s3-server-rhel7:{{ cns_release_tag }}"
  - "rhgs3/rhgs-gluster-block-prov-rhel7:{{ cns_release_tag }}"

other_images:
  - "rhscl/postgresql-95-rhel7"
  - "rhscl/ruby-23-rhel7"

non_rh_images:
  - "siamaksade/mapit"
...
