---

deploy_mirror: false
image_src: registry.redhat.io
ose_major_tag: v3.11.98
ose_release_tag: v3.11
cns_release_tag: v3.11
ose_deployer_tag: latest
image_source: registry.redhat.io
logging: v3.11.98

ose_core_images:
  - openshift3/csi-attacher:{{ ose_major_tag }}
  - openshift3/csi-driver-registrar:{{ ose_major_tag }}
  - openshift3/csi-livenessprobe:{{ ose_major_tag }}
  - openshift3/csi-provisioner:{{ ose_major_tag }}
  - openshift3/image-inspector:{{ ose_major_tag }}
  - openshift3/ose-cli:{{ ose_major_tag }}
  - openshift3/ose-cluster-capacity:{{ ose_major_tag }}
  - openshift3/ose-deployer:{{ ose_major_tag }}
  - openshift3/ose-descheduler:{{ ose_major_tag }}
  - openshift3/ose-docker-builder:{{ ose_major_tag }}
  - openshift3/ose-docker-registry:{{ ose_major_tag }}
  - openshift3/ose-egress-dns-proxy:{{ ose_major_tag }}
  - openshift3/ose-egress-http-proxy:{{ ose_major_tag }}
  - openshift3/ose-egress-router:{{ ose_major_tag }}
  - openshift3/ose-prometheus-operator:{{ ose_major_tag }}
  - openshift3/grafana:{{ ose_major_tag }}
  - openshift3/ose-haproxy-router:{{ ose_major_tag }}
  - openshift3/ose-hyperkube:{{ ose_major_tag }}
  - openshift3/ose-hypershift:{{ ose_major_tag }}
  - openshift3/ose-keepalived-ipfailover:{{ ose_major_tag }}
  - openshift3/ose-pod:{{ ose_major_tag }}
  - openshift3/ose-docker-builder:{{ ose_major_tag }}
  - openshift3/ose-node-problem-detector:{{ ose_major_tag }}
  - openshift3/ose-recycler:{{ ose_major_tag }}
  - openshift3/ose-web-console:{{ ose_major_tag }}
  - openshift3/ose-node:{{ ose_major_tag }}
  - openshift3/ose-control-plane:{{ ose_major_tag }}
  - openshift3/registry-console:{{ ose_major_tag }}
  - openshift3/snapshot-controller:{{ ose_major_tag }}
  - openshift3/snapshot-provisioner:{{ ose_major_tag }}
  - openshift3/ose-console:{{ ose_major_tag }}
  - rhel7/etcd
  - openshift3/ose-configmap-reloader:{{ ose_major_tag }}
  - openshift3/ose-cluster-monitoring-operator:{{ ose_major_tag }} 
  - openshift3/ose:latest
  - openshift3/ose:{{ ose_major_tag }}
  - rhel7/etcd:latest
  - openshift3/ose-prometheus-config-reloader:{{ ose_major_tag }}
  - openshift3/ose-kube-rbac-proxy:{{ ose_major_tag }}
  - openshift3/ose-kube-state-metrics:{{ ose_major_tag }}

ose_infra_images:
#  - "openshift3/ose-logging-auth-proxy:{{ ose_major_tag }}"
  - "openshift3/ose-logging-curator5:{{ ose_major_tag }}"
  - "openshift3/ose-logging-elasticsearch5:{{ ose_major_tag }}"
  - "openshift3/ose-logging-eventrouter:{{ ose_major_tag }}"
  - "openshift3/ose-logging-fluentd:{{ ose_major_tag }}"
  - "openshift3/ose-logging-kibana5:{{ ose_major_tag }}"
  - "openshift3/oauth-proxy:{{ ose_major_tag }}"
  - "openshift3/metrics-cassandra:{{ ose_major_tag }}"
  - "openshift3/metrics-hawkular-metrics:{{ ose_major_tag }}"
  - "openshift3/metrics-hawkular-openshift-agent:{{ ose_major_tag }}"
  - "openshift3/metrics-heapster:{{ ose_major_tag }}"
  - "openshift3/metrics-schema-installer:{{ ose_major_tag }}"
  - "openshift3/prometheus:{{ ose_major_tag }}"
  - "openshift3/prometheus:{{ ose_major_tag }}"
  - "openshift3/prometheus-alert-buffer:{{ ose_major_tag }}"
  - "openshift3/prometheus-alert-buffer:{{ ose_major_tag }}"
  - "openshift3/prometheus-node-exporter:{{ ose_major_tag }}"
  - "openshift3/prometheus-node-exporter:{{ ose_major_tag }}"
  - "openshift3/prometheus-alertmanager:{{ ose_major_tag }}"
  - "openshift3/ose-deployer:{{ ose_major_tag }}"
  - "openshift3/ose-deployer:{{ ose_major_tag }}"
  - "openshift3/logging-deployer:{{ ose_deployer_tag }}"
  - "openshift3/metrics-deployer:{{ ose_deployer_tag }}"

cns_core_images:
  - "rhgs3/rhgs-volmanager-rhel7:{{ cns_release_tag }}"
  - "rhgs3/rhgs-server-rhel7:{{ cns_release_tag }}"
  - "rhgs3/rhgs-s3-server-rhel7:{{ cns_release_tag }}"
  - "rhgs3/rhgs-gluster-block-prov-rhel7:{{ cns_release_tag }}"

other_images:
  - "rhscl/postgresql-95-rhel7"
  - "rhscl/ruby-23-rhel7"
  - "rhscl/php-71-rhel7"

non_rh_images:
  - "siamaksade/mapit"
...
