---

  - name: install ose base packages
    yum: name={{ item }} state=present
    with_items:
      - vim
      - wget
      - git
      - net-tools
      - bind-utils
      - etcd
      - docker
      - iptables-services
      - bridge-utils
      - bash-completion
      - atomic-openshift-clients
      - dnsmasq
      - atomic-openshift-utils
      - atomic-openshift-excluder-3.7.14-1.git.0.4b35b2d.el7.noarch
      - atomic-openshift-docker-excluder-3.7.14-1.git.0.4b35b2d.el7.noarch
      - haveged

  - name: remove firewalld
    yum: name=firewalld state=absent

  - name: install ose storage packages
    yum: name={{ item }} state=present
    with_items:
      - nfs-utils
      - glusterfs-fuse
      - ceph-common
      - iscsi-initiator-utils

  - name: remove openshift packages from filter
    shell: atomic-openshift-excluder unexclude

  - name: create iptables config
    copy: src=iptables dest=/etc/sysconfig/

  - name: restart iptables 
    service: name=iptables state=started enabled=yes

...
