---

  - name: install ose base packages
    yum: name={{ item }} state=present
    with_items:
      - vim
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - dnsmasq
      - haveged
      - openshift-ansible-roles-3.7.14-1.git.0.4b35b2d.el7.noarch
      - openshift-ansible-docs-3.7.14-1.git.0.4b35b2d.el7.noarch
      - openshift-ansible-lookup-plugins-3.7.14-1.git.0.4b35b2d.el7.noarch
      - openshift-ansible-filter-plugins-3.7.14-1.git.0.4b35b2d.el7.noarch
      - openshift-ansible-3.7.14-1.git.0.4b35b2d.el7.noarch
      - atomic-openshift-utils-3.7.14-1.git.0.4b35b2d.el7.noarch
      - atomic-openshift-3.7.14-1.git.0.593a50e.el7.x86_64
      - atomic-openshift-excluder-3.7.14-1.git.0.593a50e.el7.noarch
      - atomic-openshift-docker-excluder-3.7.14-1.git.0.593a50e.el7.noarch
      - openshift-ansible-callback-plugins-3.7.14-1.git.0.4b35b2d.el7.noarch
      - openshift-ansible-playbooks-3.7.14-1.git.0.4b35b2d.el7.noarch
      - atomic-openshift-clients-3.7.14-1.git.0.593a50e.el7.x86_64

  - name: remove firewalld
    yum: name=firewalld state=absent

  - name: install ose storage packages
    yum: name={{ item }} state=present
    with_items:
      - nfs-utils
      - glusterfs-fuse
      - ceph-common
      - iscsi-initiator-utils

  - name: remove openshift packages from filter
    shell: atomic-openshift-excluder unexclude

  - name: create iptables config
    copy: src=iptables dest=/etc/sysconfig/

  - name: restart iptables 
    service: name=iptables state=started enabled=yes

...
