---
- name: install local repository packages
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - createrepo
    - yum-utils

- name: install package but disable gluster repo
  shell: yum install --disablerepo=rh-gluster-3-web-admin-server-for-rhel-7-server-rpms -y python2-pyasn1-0.1.9-7.el7.noarch

- name: make repository directory
  file: state=directory owner=apache group=apache mode=755 path=/var/www/html/repo

- name: start httpd
  service: name=httpd state=restarted

- name: Download package
  shell: yum install --downloadonly "{{ item }}" --downloaddir=/var/www/html/repo
  with_items:
    - "{{ ose_packages }}"
    - "{{ storage_packages }}"

- name: own repository items
  file: state=directory owner=apache group=apache mode=755 recurse=yes path=/var/www/html/repo

- name: createrepo
  shell: createrepo /var/www/html/repo

- name: install ose base packages
  shell: "yum localinstall /var/www/html/repo/*"

- name: remove firewalld
  yum: name=firewalld state=absent

- name: remove openshift packages from filter
  shell: atomic-openshift-excluder unexclude

- name: create iptables config
  copy: src=iptables dest=/etc/sysconfig/

- name: restart iptables 
  service: name=iptables state=started enabled=yes

...
