---

- block:

  - name: Update using RHUI while its still attached
    yum:
      name: '*'
      state: latest

  - name: remove rhui-client packages
    yum: name=rh-amazon-rhui-client* state=absent

  - name: clean yum cache
    shell:
      cmd: yum clean all
      warn: false
    ignore_errors: true

  - name: enable Red Hat product id support in yum
    copy: src=product-id.conf dest=/etc/yum/pluginconf.d/

  when: disable_rhui

- name: ensure organization id is supplied
  fail:
    msg: "You must supply an RHSM organization ID"
  when:
    - (rhsm_org_id is not defined or rhsm_org_id == "")

- name: ensure activation key is supplied
  fail:
    msg: "You must supply an RHSM activation key"
  when:
    - (rhsm_act_key is not defined or rhsm_act_key == "" )

- name: ensure repositories are supplied
  fail:
    msg: "You must supply at least one RHSM repository"
  when:
    - (rhsm_repos is not defined or rhsm_repos|length == 0)

- name: registering system with CDN
  redhat_subscription:
    org_id: "{{ rhsm_org_id }}"
    activationkey: "{{ rhsm_act_key }}"
    state: present

- name: ensure that gluster pool is attached
  shell: subscription-manager attach --pool="{{ gluster }}"

- name: disable all default repositories
  shell: subscription-manager repos --disable="*"

- name: enable all required repositories
  shell: subscription-manager repos --enable {{ rhsm_repos | join(" --enable ") }}

...
