---
  - name: enable extras
    shell: subscription-manager repos --enable rhel-7-server-extras-rpms

  - name: install docker
    yum: name=docker state=present

  - name: install docker registry
    yum: name=docker-distribution.x86_64 state=present

  - name: start registry
    service: name=docker-distribution state=started

  - name: install dependencies
    yum: name=docker-python state=present

  - name: create docker storage config
    copy: src=docker-storage-setup dest=/etc/sysconfig/

  - name: create docker storage config
    copy: src=registries.conf dest=/etc/containers/registries.conf

  - name: install skopeo while extras enabled
    yum: name=skopeo state=present

  - name: install python-docker-py while extras enabled
    yum: name=python-docker-py state=present

  - name: start docker
    service: name=docker state=started enabled=yes

  - name: disable extras
    shell: subscription-manager repos --disable rhel-7-server-extras-rpms

...
