---

- hosts: masters

  tasks:

    - name: parse master-config as json
      shell: cat /etc/origin/master/master-config.yaml | python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' > /tmp/master-config-old.json
      args:
        creates: /tmp/master-config-old.json

    - name: add required configuration to enable pv resize to json
      shell: "cat /tmp/master-config-old.json | jq '.kubernetesMasterConfig.apiServerArguments += {\"feature-gates\":[\"ExpandPersistentVolumes=true\"]}' | jq '.kubernetesMasterConfig.controllerArguments += {\"feature-gates\":[\"ExpandPersistentVolumes=true\"]}' | jq '.admissionConfig += {\"PersistentVolumeClaimResize\": {\"configuration\": {\"apiVersion\": \"v1\", \"disable\": false, \"kind\": \"DefaultAdmissionConfig\"}}}' > /tmp/master-config-new.json"
      args:
        creates: /tmp/master-config-new.json

    - name: parse json to yaml
      shell: cat /tmp/master-config-new.json | python -c 'import sys, yaml, json; yaml.safe_dump(json.load(sys.stdin), sys.stdout, allow_unicode=True, default_flow_style=False)' > /etc/origin/master/master-config.yaml

    - name: restart master services
      service: name={{ item }} state=restarted
      with_items:
        - atomic-openshift-master-api.service
        - atomic-openshift-master-controllers.service

    - name: Add  as the system-wide default
      command: "oc patch storageclass glusterfs-storage -p '{\"allowVolumeExpansion\": true }'"

...
